<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSCOKzNp\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSCOKzNp/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSCOKzNp.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSCOKzNp\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSCOKzNp\App_KernelDevDebugContainer([
    'container.build_hash' => 'SCOKzNp',
    'container.build_id' => '4a604e5f',
    'container.build_time' => 1716745083,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSCOKzNp');
