<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTiTkXEo\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTiTkXEo/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTiTkXEo.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTiTkXEo\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTiTkXEo\App_KernelDevDebugContainer([
    'container.build_hash' => 'TiTkXEo',
    'container.build_id' => '76edadda',
    'container.build_time' => 1713004113,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTiTkXEo');
