<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Usuario extends \App\Entity\Usuario implements \Doctrine\ORM\Proxy\InternalProxy
{
     use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'alumnos' => [parent::class, 'alumnos', null],
        "\0".parent::class."\0".'apellidos' => [parent::class, 'apellidos', null],
        "\0".parent::class."\0".'dni' => [parent::class, 'dni', null],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null],
        "\0".parent::class."\0".'fecha_nacimiento' => [parent::class, 'fecha_nacimiento', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'mensajes' => [parent::class, 'mensajes', null],
        "\0".parent::class."\0".'nombre' => [parent::class, 'nombre', null],
        "\0".parent::class."\0".'password' => [parent::class, 'password', null],
        "\0".parent::class."\0".'profesors' => [parent::class, 'profesors', null],
        "\0".parent::class."\0".'rol' => [parent::class, 'rol', null],
        'alumnos' => [parent::class, 'alumnos', null],
        'apellidos' => [parent::class, 'apellidos', null],
        'dni' => [parent::class, 'dni', null],
        'email' => [parent::class, 'email', null],
        'fecha_nacimiento' => [parent::class, 'fecha_nacimiento', null],
        'id' => [parent::class, 'id', null],
        'mensajes' => [parent::class, 'mensajes', null],
        'nombre' => [parent::class, 'nombre', null],
        'password' => [parent::class, 'password', null],
        'profesors' => [parent::class, 'profesors', null],
        'rol' => [parent::class, 'rol', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
