<?php

namespace ContainerPw3xLlA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JWdUnm1Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.JWdUnm1' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.JWdUnm1'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'menu' => ['privates', 'App\\Repository\\MenuRepository', 'getMenuRepositoryService', true],
        ], [
            'menu' => 'App\\Repository\\MenuRepository',
        ]);
    }
}
