<?php

namespace ContainerPw3xLlA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Gy52x5LService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Gy52x5L' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Gy52x5L'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'ar' => ['privates', 'App\\Repository\\AlumnoRepository', 'getAlumnoRepositoryService', true],
            'cr' => ['privates', 'App\\Repository\\ClaseRepository', 'getClaseRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'serializer' => ['privates', 'debug.serializer', 'getDebug_SerializerService', false],
            'ur' => ['privates', 'App\\Repository\\UsuarioRepository', 'getUsuarioRepositoryService', true],
        ], [
            'ar' => 'App\\Repository\\AlumnoRepository',
            'cr' => 'App\\Repository\\ClaseRepository',
            'entityManager' => '?',
            'serializer' => '?',
            'ur' => 'App\\Repository\\UsuarioRepository',
        ]);
    }
}
